<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>name</key>
<string>Adblock Plus Filter List</string>
<key>scopeName</key>
<string>text.abp</string>
<key>uuid</key>
<string>93af9947-d7f6-437c-9ffb-dd8c27d2ede8</string>
<key>firstLineMatch</key>
<string>^(?i:\s*\[\s*(?:adblock\s*(plus\s*(\d+(\.\d+)*\s*)?)?)\]\s*)$</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>meta.abp.header</string>
<key>comment</key>
<string>Header</string>
<key>match</key>
<string>^\s*\[.*\]\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.comment</string>
<key>comment</key>
<string>Comment</string>
<key>begin</key>
<string>^\s*\!\s*([a-zA-Z0-9\-_ ]*)(\s*:\s*(.*))?</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.comment.key</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.comment.value</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.snippet</string>
<key>begin</key>
<string>^(.*)(#\$#)(.*)</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.options.snippet</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>abp.separator.snippet</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.call.snippet</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.elemhide.exception</string>
<key>begin</key>
<string>^(.*)(#@#)(.*)</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.options.elemhide.exception</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>abp.separator.elemhide.exception</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.selector.elemhide.exception</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.elemhide.extended</string>
<key>begin</key>
<string>^(.*)(#\?#)(.*)</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.options.elemhide.extended</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>abp.separator.elemhide.extended</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.selector.elemhide.extended</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.elemhide.default</string>
<key>begin</key>
<string>^([^#]*)(##)(.*)</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.options.elemhide.default</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>abp.separator.elemhide.default</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.selector.elemhide.default</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.blocking.exception</string>
<key>begin</key>
<string>^(@@)([^\$]*)((\$)(.*))?</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.separator.blocking.exception</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>abp.selector.blocking.exception</string>
</dict>
<key>4</key>
<dict>
<key>name</key>
<string>abp.separator.blocking.exception</string>
</dict>
<key>5</key>
<dict>
<key>name</key>
<string>abp.options.blocking.exception</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
<dict>
<key>name</key>
<string>abp.blocking.default</string>
<key>begin</key>
<string>^([^\$]*)((\$)(.*))?</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>abp.selector.blocking.default</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>abp.separator.blocking.default</string>
</dict>
<key>4</key>
<dict>
<key>name</key>
<string>abp.options.blocking.default</string>
</dict>
</dict>
<key>end</key>
<string>\s*$</string>
</dict>
</array>
</dict>
</plist>
